# .streamlit/secrets.example.toml
# -------------------------------------------------
# Fülle die Platzhalter in "" mit deinen echten Werten
# -------------------------------------------------

secrets_password    = "YOUR_SECRETS_PASSWORD"
client_id           = "YOUR_CLIENT_ID"
client_secret       = "YOUR_CLIENT_SECRET"
username            = "YOUR_USERNAME"
password            = "YOUR_PASSWORD"

storage_type        = "s3"                       # oder "local"
aws_access_key_id   = "YOUR_AWS_ACCESS_KEY_ID"
aws_secret_access_key = "YOUR_AWS_SECRET_KEY"
s3_bucket_name      = "arn:aws:s3:::YOUR_BUCKET_NAME"
aws_region          = "YOUR_AWS_REGION"          # z. B. "eu-west-1"
